language: c

os:
  - linux
  #- osx

compiler:
  - gcc
  #- clang

cache:
  directories:
    #- /usr/local/include
    #- /usr/local/lib
    - /home/travis/allegro5

before_install:
    - if [ `uname` = "Linux" ]; then
         export DISPLAY=:99.0;
         sh -e /etc/init.d/xvfb start;
         sudo apt-get update;
         sudo apt-get install -y libvorbis-dev libtheora-dev libwebp-dev libphysfs-dev libopusfile-dev libdumb1-dev libflac-dev libpulse-dev libgtk2.0-dev pandoc libcurl4-nss-dev libenet-dev pulseaudio libasound2-dev libopenal-dev;
      elif [ `uname` = "Darwin" ]; then
         brew update && brew install opusfile libvorbis webp freetype flac physfs dumb theora enet;
      fi

env:
  - WANT_SHADERS_GL=off
  #- WANT_SHADERS_GL=on

script:
    - |
      if [ ! -d /home/travis/allegro5 ]; then
         export USE_CACHE=0;
         git clone https://github.com/liballeg/allegro5.git;
         cd allegro5;
         mkdir build;
         cd build;
      else
         export USE_CACHE=1;
         cd allegro5/build;
      fi
      if [ `uname` = "Linux" ]; then
         if [ `USE_CACHE` = 0 ]; then
            cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWANT_SHADERS_GL=$WANT_SHADERS_GL;
            make;
         else
            echo USING CACHE;
         fi
         sudo make install;
         sudo ldconfig;
      elif [ `uname` = "Darwin" ]; then
         cmake .. -DWANT_SHADERS_GL=$WANT_SHADERS_GL -G Xcode;
         xcodebuild;
      fi
    # DNF FROM HERE ON
    - cd ..
    - cd ..
    - git clone https://github.com/LukeMS/absdatatypes-c.git
    - cd absdatatypes-c && sudo make install --file=linux.makefile && cd ..
    - git clone https://github.com/LukeMS/zhash-c.git
    - cd zhash-c && sudo make install --file=linux.makefile && cd ..
    - git clone https://github.com/LukeMS/eventmgr-c.git
    - cd eventmgr-c && sudo make install --file=linux.makefile && cd ..
    - make all --file=linux.makefile
    - make run --file=linux.makefile
    - cat dnf_log.txt
