language: c

os:
  - linux
  #- osx

compiler:
  - gcc
  #- clang

cache:
  directories:
    - ~/allegro5

env:
  - WANT_SHADERS_GL=off
  #- WANT_SHADERS_GL=on

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libvorbis-dev libtheora-dev libwebp-dev libphysfs-dev libopusfile-dev libdumb1-dev libflac-dev libpulse-dev libgtk2.0-dev pandoc libcurl4-nss-dev libenet-dev pulseaudio libasound2-dev libopenal-dev

script:
  - cd ~
  - make dep_allegro      --file=linux.makefile
  - make dep_absdatatypes --file=linux.makefile
  - make dep_zhash        --file=linux.makefile
  - make dep_eventmgr     --file=linux.makefile
  - make all              --file=linux.makefile
  - make run              --file=linux.makefile
  - cat dnf_log.txt
