language: c
before_install:
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:allegro/5.2
  - sudo apt-get install liballegro5-dev valgrind --force-yes
  - git clone https://github.com/LukeMS/absdatatypes-c.git
  - cd absdatatypes-c && sudo make install --file=linux.makefile && cd ..
  - git clone https://github.com/LukeMS/zhash-c.git
  - cd zhash-c && sudo make install --file=linux.makefile && cd ..
  - git clone https://github.com/LukeMS/eventmgr-c.git
  - cd eventmgr-c && sudo make install --file=linux.makefile && cd ..
install:
  - make all --file=linux.makefile
script:
  #- make valgrind --file=linux.makefile
  - make run --file=linux.makefile
after_script: