language: c

os:
  - linux
  #- osx

compiler:
  - gcc
  #- clang

cache:
  directories:
    - $TRAVIS_BUILD_DIR/allegro5

env:
  - WANT_SHADERS_GL=off
  #- WANT_SHADERS_GL=on

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libvorbis-dev libtheora-dev libwebp-dev libphysfs-dev libopusfile-dev libdumb1-dev libflac-dev libpulse-dev libgtk2.0-dev pandoc libcurl4-nss-dev libenet-dev pulseaudio libasound2-dev libopenal-dev

script:
  - cd $TRAVIS_BUILD_DIR && make --file=linux.makefile dep_allegro
  - cd $TRAVIS_BUILD_DIR && make --file=linux.makefile dep_absdatatypes
  - cd $TRAVIS_BUILD_DIR && make --file=linux.makefile dep_zhash        
  - cd $TRAVIS_BUILD_DIR && make --file=linux.makefile dep_eventmgr     
  - cd $TRAVIS_BUILD_DIR && make --file=linux.makefile run
  - cat dnf_log.txt
