language: c
before_install:
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:allegro/5.2
  - sudo apt-get -y -f install liballegro5-dev valgrind
  - git clone https://github.com/LukeMS/absdatatypes-c.git
  - cd absdatatypes-c && sudo make install --file=linux.makefile && cd ..
  - git clone https://github.com/LukeMS/zhash-c.git
  - cd zhash-c && sudo make install --file=linux.makefile && cd ..
  - git clone https://github.com/LukeMS/eventmgr-c.git
  - cd eventmgr-c && sudo make install --file=linux.makefile && cd ..
  # improve gdb messages
  - git clone https://github.com/jeremie-koenig/glibc /opt/src/glibc
install:
  - make all --file=linux.makefile
before_script:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - ls -A resources/gfx/tile_feature/
script:
  - make gdb --file=linux.makefile
  #- make run --file=linux.makefile # segmentation fault
  #- make valgrind --file=linux.makefile # lots of errors
after_script:
  - cat dnf_log.txt